### ISSUE TITLE
User Registration Implementation

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#10]
Mentor : @sr6033
**Brief**
User registration implementation should take :
* Alias (Username)
* Password
* Email Address
* Short Bio
* Age
* Country

There should also be a verification email sent to that address after generating a unique verification token and link. Accessing that specific link only will mark the user as 'Verified' which will be updated in the same user's document in database.

**Requirements**
A single POST `/signup` route which should :
1. Take the above fields, and a (re)Captcha as parameters.
2. Generate encrypted password
3. Generate and send a verification code and link to the provided email **\***
4. Store the user in database with suitable data.

Next logical requirement is to write a GET `/verify` which takes the parameters from the URL and checks them if the are legit or not. Finally, on successful match, user is marked as Verified.

**Notes**
Password encryption and verification token generation should use strong encryption techniques. Please discuss about the encryption methods which you'd wish to implement.

This is to be implemented from scratch, and would thus require patience and maximum interaction with mentors and admin. Please feel free to raise doubts on Slack or here itself.

**Comment by adarshlilha** [comment]
I would like to work on this issue

**Comment by sr6033** [comment]
For now, I am handing this issue to @adarshlilha.
@syedjahangirpeeran you will get a chance if @adarshlilha is not able to complete it by deadline.

@adarshlilha  What date will be good for your evaluation?

**Comment by adarshlilha** [comment]
@sr6033 I will be completing this task by tomorrow EOD. Will reach out in case of any doubts.

**Comment by sr6033** [comment]
Okay.

**Comment by sr6033** [comment]
Any updates @adarshlilha ?

**Comment by sakshamsaxena** [comment]
De-assigning @adarshlilha and assigning 
@syedjahangirpeeran

**Comment by sakshamsaxena** [comment]
Assigned @IamRaviTejaG

**Comment by IamRaviTejaG** [comment]
@sakshamsaxena Fixed this!

**Comment by mohitj27** [comment]
Is this issue available or already done 
If available can I work on this

**Comment by sakshamsaxena** [comment]
@mohitj27 Hey, I have updated the task description. You can start to work on it, and me and @sr6033 can help you along with it.
