### ISSUE TITLE
Authentication for Protected Routes

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#11]
Mentor : @aakashrstg00
**Brief**
To consume any protected routes in any Public API like twitter and Github, they use various authentication methods. We wish to implement an Express Middleware to check for that authentication.

**Requirements**
The Authentication Middleware should :
1. Check the HTTP Request Object received.
2. Extract and verify suitable headers and info from it.
3. Generate an appropriate response.

Further, a thorough guide on how to generate tokens for authentication would need to be written. 

**Notes**
There are many auth methods which we can use and take inspiration from, so it is completely up to the participant to suggest a brief workflow of the same before implementing it. Mentors and admins will promptly respond to your ideas and will help as per need to implement those.

This is to be implemented from scratch, and would thus require patience and maximum interaction with mentors and admin. Please feel free to raise doubts on Slack or here itself.

Please discuss about the encryption methods which you'd wish to implement on passwords and verification link.

**Comment by IamRaviTejaG** [comment]
I'd like to work on this! Please assign it to me!

**Comment by sakshamsaxena** [comment]
Yep sure you can start on it!

**Comment by IamRaviTejaG** [comment]
@sakshamsaxena Since presently everything is public, I think a signup route should be added. Once that has been done, every user will be given a key (kind of a API key) which he will have to send on every request (via headers), and if he doesn't, he would be denied access.

**Comment by sakshamsaxena** [comment]
Writing some code to obtain the key and to process it via a flow is the primary aim of this issue. You've to basically implement a middleware for this. A static key lookup is rather too simple, and that's why it's encouraged to come up with a good encryption flow. Remember that Uzay is an API which would be consumed by programs only, and not humans directly, and so it's okay to design a robust and heavily encrypted flow than a simple one.

**Comment by IamRaviTejaG** [comment]
@sakshamsaxena The general widespread practice includes authentication/sessions using `passport` and `jsonwebtoken` modules. Is it exactly what needs to be implemented?

**Comment by sakshamsaxena** [comment]
@IamRaviTejaG please keep a PR open whenever you make your first commit. It'll help us also to keep a track of your progress, and would serve a better conversation place
