### ISSUE TITLE
Creating an Unix Installation Script for installing the entire project

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#13]
Mentor : @aakashrstg00
**Brief**
Presently we need to follow the steps manually in README to install the project. We wish to have a Bash Script to do it for us instead.

**Requirements**
Write a Bash/Shell Script which would check and execute each installation step and produce suitable outputs in cases of success and failures.

**Comment by sakshamsaxena** [comment]
Sure @devshiva619 
Let me and @aakashrstg00 know about your progress or doubts!

**Comment by devshiva619** [comment]
@sakshamsaxena @aakashrstg00 I have one doubt, like I have made script to install till node, mongodb, and nodemon. 
Can I now just display commands that user need to do next like run `mongod` and then add the 4 commands and then `run start` ??

**Comment by aakashrstg00** [comment]
should be fine.

**Comment by sakshamsaxena** [comment]
It's a topcoder task so I think it'd be worth it if it goes till npm start.

Regards
Saksham Saxena

________________________________

**Comment by sakshamsaxena** [comment]
@devshiva619 by when do you plan to submit this for review? Please keep a PR open meanwhile

**Comment by sakshamsaxena** [comment]
@devshiva619 What's your progress ? Could you send the PR by tonight?

**Comment by devshiva619** [comment]
@sakshamsaxena extremely sorry, I missed you previous comment.
I am trying to figure out one part. I will try to do it by tonight.

**Comment by sakshamsaxena** [comment]
@devshiva619 Sure, that's fine. You can open a PR meanwhile and keep adding commits to it, if you're comfortable that way for review.

**Comment by sakshamsaxena** [comment]
@devshiva619 Can you submit a PR by tonight ?

**Comment by devshiva619** [comment]
Hey @sakshamsaxena I am working on the same, trying to do some work around where I am getting stuck.
Can I do it by tomorrow morning 10am? If it is fine? Orelse I will do it by tonight.

**Comment by devshiva619** [comment]
@sakshamsaxena I have made a PR, with WIP tag.

**Comment by sakshamsaxena** [comment]
Closing this in favour of better alternatives for environment setup.
