### ISSUE TITLE
Make code ES6 compliant & use StandardJS style guide

### ISSUE THREAD

**Issue by IamRaviTejaG** [sakshamsaxena/uzay#15]
The code uses normal callback functions, 8 spaces indent etc, which are not as per the latest standards, so I suggest that the code be upgraded.

Example:
`CommentMapper.GetCommentsByPostID = function(id, includeComments) { // do something }`

should be written as:

`CommentMapper.GetCommentsByPostID = (id, includeComments) => { // do something }`

Also the code can be styled as per the StandardJS style guide: https://github.com/standard

**Would you like to work on this?**
Yes!

**Comment by sakshamsaxena** [comment]
Hey, thanks for bringing this to my attention. As of now, I'm using old jslint and stuff with grunt. I think that's pretty obsolete too. Anyways, I'm okay with syntactic style changes as long as they're helping to reduce redundancy in code. In case of indentation and arrow functions of the like, I'm not so willing to shift to that. 

Feel free to optimise any code you find here, and can also get some points by addressing the implementing husky task. You can also help in migrating to eslint from jslint, I've not ventured down there yet. 

I'll keep this open for further consideration, thanks!

**Comment by IamRaviTejaG** [comment]
@sakshamsaxena Please add some tags to this issue so that appropriate people can work on it. 😄

**Comment by sakshamsaxena** [comment]
538b2db

**Comment by IamRaviTejaG** [comment]
@sakshamsaxena Great work sir!
