### ISSUE TITLE
Make a Post-Install Script in Node

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#19]
Mentor : @sakshamsaxena
**Brief**
Non-UNIX users can't copy the config.sample.js after installation of project. We want a small postinstall node script which gracefully copies this file as config.js.

**Requirements**
Write a Node.js Script which would copy `config.sample.js` to `config.js` in the same folder. Include this script in package.json as postinstall script. This script must also be kept in the config folder. Feel free to use any NPM module or native node functionality to implement this.

**Comment by sakshamsaxena** [comment]
@IamRaviTejaG Since you have tackled two Issues already with TopCoder/Pro levels, I can't really assign an Intermediate Issue to you. Sorry! Hope you understand :smile:

**Comment by vikasgola** [comment]
@sakshamsaxena I want to work on this.

**Comment by sakshamsaxena** [comment]
@vikasgola you can start on it

**Comment by sakshamsaxena** [comment]
Addressed in #21
