### ISSUE TITLE
Write Comments' Like/Dislike Routes

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#6]
Mentors : @sr6033
**Brief Idea**
In Uzay, we have implemented a blank route to get or set a like/dislike reaction on a particular blog post. We also want the same like/dislike behaviour on a comment as well. 

**Required End Results**
1. A blank RESTful route, something similar to existing BlogPost like/dislike route, for Comments.

**Notes**
Take inspiration from other blank pending routes. The task is only to write the blank route, hence a cakewalk task. 
Please also follow the guidelines mentioned in CONTRIBUTING.md for development.

**Comment by sourabh1031** [comment]
I would like to take up this issue

**Comment by sakshamsaxena** [comment]
@sourabh1031 Hey, you can read the Contributing and Readme guide to set up the project on your system. Then you can analyse and study a bit on how the Blog and User Routes are implemented. Some are implemented and some are yet to be. You need to take inspiration from those and write blank routes as per the task requirements. You need to have some idea about Express.js for this.

**Comment by mohit2016** [comment]
This is the easiest one, Can I contribute? Please let me know if i need to solve.

**Comment by sourabh1031** [comment]
@mohit2016 if you don't mind but the issue has been assigned to me

**Comment by mohit2016** [comment]
@sourabh1031 cool... no prob good luck 👍 :-)

**Comment by sr6033** [comment]
@sourabh1031 What will be your deadline?

**Comment by sr6033** [comment]
Goodluck then. I will wait for your PR.

**Comment by sakshamsaxena** [comment]
Merged #14
