### ISSUE TITLE
Write CRUD Operations for all Mappers

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#7]
Mentors : @aakashrstg00
**Brief Idea**
In Uzay, we have implemented some of the CRUD operations in some of the Mappers as of now. We wish to have CRUD operations implemented in the same existing way using the same existing pattern for the remaining places.

**Required End Results**
All CRUD operations for all the Mappers should be implemented using Mongoose operations. 

**Notes**
The task is to implement these operations which seem useful. It is not 100% necessary that all the CRUD would apply, so you are required to be thoughtful about the design while implementing it. Feel free to discuss doubts here or on Slack Channel/DM.

Please also follow the guidelines mentioned in CONTRIBUTING.md for development.

**Comment by sourabh1031** [comment]
@sakshamsaxena I would like to work on the issue.Actually i now mongo at a very basic level .Can you plese provide me some help so that i can hack this issue.I want to learn by doing

**Comment by aakashrstg00** [comment]
yes @sourabh1031 
go have a look at how mongoose is a mongo driver for nodejs and its methods.

**Comment by ashwani99** [comment]
If anyone is not working on this, can I take this up please?

**Comment by sourabh1031** [comment]
@ashwani99 i am working can you give littlle more time to work

**Comment by sakshamsaxena** [comment]
@ashwani99 can you finish this by Saturday night ?

**Comment by ashwani99** [comment]
@sakshamsaxena Sure, I will try. Can you please tell me which all CRUD operations for which mappers you want to be added?

**Comment by sakshamsaxena** [comment]
All four CRUD for blog post and comment, create, read, update for tags and users.
