### ISSUE TITLE
Implement Husky

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#8]
Mentor : @aakashrstg00
**Brief Idea**
[Husky](https://www.npmjs.com/package/husky) is a great tool which helps new developers and contributors write and push quality code to OSS Projects. We wish to have it implemented in Uzay as well.

**Required End Results**
Implement Husky for precommit scenarios, and also suitably update the README and Contributing pages.

**Notes**
It is important to implement as well as correctly document the usage in existing documentation to get the points. Feel free to discuss doubts here or on Slack Channel/DM.

Please also follow the guidelines mentioned in CONTRIBUTING.md for development.

**Comment by thisisabdus** [comment]
Hey, can I work on this issue?

**Comment by sakshamsaxena** [comment]
@thisisabdus Yeah sure!

**Comment by sakshamsaxena** [comment]
@thisisabdus Hey, will you be working on this anytime soon ?

**Comment by sakshamsaxena** [comment]
Closed in #24
