### ISSUE TITLE
Implement SuperTest for Testing

### ISSUE THREAD

**Issue by sakshamsaxena** [sakshamsaxena/uzay#9]
Mentors : @anshumanv
**Brief Idea**
[SuperTest](https://www.npmjs.com/package/supertest) is a tool which helps to test HTTP Routes. We wish to have it implemented in Uzay as well for Testing Suite.

**Required End Results**
* [x] Implement SuperTest to at least 12 existing Tests.
* [ ] Create  4 new Tests and implement SuperTest in them too. 

The new cases should test for bad Routes (incorrect or invalid URLs), as currently we are testing all good ones.

**Notes**
The 4 new tests should not be in the same "describe" section. All should be in different "describe" sections, only then points will be awarded. Feel free to discuss doubts here or on Slack Channel/DM.

Please also follow the guidelines mentioned in CONTRIBUTING.md for development.

**Comment by anshumanv** [comment]
All the best @Ace-Bansal! :smile:

**Comment by sakshamsaxena** [comment]
@Ace-Bansal do keep a PR opened so that we know about your progress. You can inform anytime when you're ready for a review

**Comment by Ace-Bansal** [comment]
Thanks for assigning me. I'll start right away!

**Comment by sakshamsaxena** [comment]
@Ace-Bansal Hey, could you make any progress ? We can help if you're stuck somewhere

**Comment by Ace-Bansal** [comment]
Hey, yes I did start out but I had to visit a relative urgently due to her health issues. Maybe it'd be better for the project if you reassigned it to someone else because I don't know for how long I'll be here. Sorry for the inconvenience.

**Comment by sakshamsaxena** [comment]
@Ace-Bansal You can still take it up. No one else is working on it, and there's still a month left :)

**Comment by sourabh1031** [comment]
@sakshamsaxena can i work on this ?

**Comment by anshumanv** [comment]
Sure thing @sourabh1031, all the best!

**Comment by sourabh1031** [comment]
@anshumanvI am not able to understand testing. I have read a few articles on medium and other forums but I got only the overview. can you please tell me the specific resources from where I can learn

**Comment by sakshamsaxena** [comment]
SuperAgent and Mocha docs are sufficient I think.
